            

version: '3'
services:
  node:
    image: node:alpine
    container_name: e-commerce
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=1
      - PORT=4000
    env_file:
      - .env
    networks:
      - backend-net

  redis:
    image: redis
    container_name: redis-task
    networks:
      - backend-net

  db:
    image: postgres:13
    container_name: db-sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: beshinchi_oy_imtihon
    ports:
      - '5490:5432'
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge


